### ISSUE TITLE
End-to-End Test Middleware (Fetch from Nuxt Instance)

### ISSUE THREAD

**Issue by floriankapaun** [danielroe/nuxt-vitest#127]
I'm trying to end-to-end test a middleware that redirects a user if it doesn't provide a valid auth token.

Before `nuxt-vitest` I was using `@nuxt/text-utils` to fetch a route from the test app, that the middleware was applied to.

But those two dependencies don't seem compatible with each other.

Hence I tried a lot of approaches but wasn't successful yet in fetching from the `nuxt-vitest` nuxt instance. I guess that might be because that instance doesn't load any routes/pages. Could this be the case?

Would it make more sense to get `@nuxt/test-utils` working alongside `nuxt-vitest`, or is there a way I could migrate my previous test to `nuxt-vitest`? Would be willing to provide a PR for `nuxt-vitest` if that makes sense, but I'm not quite sure if that's something that this module tries to solve.

My current workaround is to simply unit-test the middleware by importing it.

**Comment by danielroe** [comment]
You should be able to use the two alongside each other, just not within the same file.

**Comment by floriankapaun** [comment]
You are right, the two packages actually work perfectly fine alongside each other. There was a configuration problem that produced my problem. I had `jsdom` configured as global vitest environment. This setting would throw the following error whenever I ran `setup({})` from `@nuxt/test-utils`:

```
TypeError: The URL must be of scheme file

Serialized Error: {
  "code": "ERR_INVALID_URL_SCHEME",
}
```

You can check out my [stackblitz example](https://stackblitz.com/edit/nuxt-starter-xyuqfe?file=tests/utils/greet.test.ts) if you want to further investigate this behaviour but I don't see this as necessary.
