### ISSUE TITLE
Simple test super slow

### ISSUE THREAD

**Issue by andylord56** [danielroe/nuxt-vitest#142]
```
import { describe, expect, test, beforeAll } from 'vitest'
import { setup } from '@nuxt/test-utils'

describe('testing', async () => {
  await setup({})
  test('it works', () => {
    expect(true).toBe(true)
  })
})

```
![image](https://user-images.githubusercontent.com/2530510/234339022-385ce655-607a-4eb7-b707-63c8ab2aa52e.png)
65.48s is a bit slow for a simple test not sure whats causing it

**Comment by danielroe** [comment]
It's building your app (that's the `setup()` bit)... 

With `nuxt-vitest` you can omit that step if you don't need to run e2e tests against the server.
