### ISSUE TITLE
How to use when creating a module?

### ISSUE THREAD

**Issue by silverbackdan** [danielroe/nuxt-vitest#161]
Hi @danielroe - thanks for this package. I'm getting this error:
```
Failed to load nuxt-vitest module. You may need to add it to your nuxt.config.
```

My directory structure is a little different though as I'm creating a module:
https://github.com/components-web-app/cwa-nuxt-module/tree/fix/tests

I had been using another plugin but came across the same issue as was raised here relating to a missing virtual file.
https://github.com/nuxt/nuxt/issues/20550

Do you have any suggestions on the best way for me to resolve this?

**Comment by silverbackdan** [comment]
I have managed to get some tests running by creating another nuxt config in my root.

I tried importing the config from the `playground` directory but I have another package.json in there and install dependencies which would only be required by an app using the module in there. So if I just import the config from the playground then it doesn't work.

I think the root directory may need to be configurable but looking at the code I think this may be missing?

**Comment by danielroe** [comment]
Configuring this via `rootDir` is absolutely the right way to go here.

Let's track in https://github.com/danielroe/nuxt-vitest/issues/183.

You can also see this used to test a module in https://github.com/nuxt/image, but configuring with `rootDir` + overrides will be the better solution.
