### ISSUE TITLE
TypeError: `$el.isEqualNode is not a function` with pages enabled

### ISSUE THREAD

**Issue by dsvgl** [danielroe/nuxt-vitest#18]
If I have a pages directory or manually set `pages` to `true` inside nuxt.config.ts and also am using `useRuntimeConfig` (either in app.vue or spec file), I get the following error:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: $el.isEqualNode is not a function
 ❯ node_modules/.pnpm/@unhead+vue@1.0.14_vue@3.2.45/node_modules/@unhead/vue/dist/index.cjs:159:92
 ❯ node_modules/.pnpm/@unhead+vue@1.0.14_vue@3.2.45/node_modules/@unhead/vue/dist/index.cjs:159:30
 ❯ renderDOMHead node_modules/.pnpm/@unhead+vue@1.0.14_vue@3.2.45/node_modules/@unhead/vue/dist/index.cjs:148:34
```

The test itself passes, but the typeerror causes exit code 1.

Reproduction:
https://stackblitz.com/edit/github-g2mghx?file=nuxt.config.ts,test%2Fapp.spec.ts,app.vue

Run:
```
pnpm i
pnpm test:unit
```
See, that the test fails with mentioned error.

Go to nuxt.config.ts and comment-out `pages: true`.
Run `pnpm test:unit` and see that command now succeeds.

---

**Notes:**
- vitest needs up to a minute for me to run inside Stackblitz. Am I missing a config?
- runtimeConfig is always `{}` within test env – bug or feature? :)

**Comment by maicss** [comment]
Did you fix this?

**Comment by larzon83** [comment]
Sadly no
