### ISSUE TITLE
Support monorepositories / vitest workspace

### ISSUE THREAD

**Issue by TECH7Fox** [danielroe/nuxt-vitest#183]
I have a Nuxt 3 monorepo with some packages that also have Vitest tests. I set the projects in a `vitest.workspace.json` at the root of the monorepo. The other packages don't use nuxt-vitest and run fine in the workspace when I remove the nuxt-vitest project. 

When I run `vitest run` I get this error:

```
failed to load config from /home/jordy/repositories/mymonorepo/apps/myproject1/vitest.config.ts
Error: Failed to load nuxt-vitest module. You may need to add it to your nuxt.config.
```

When I run `vitest run` in `myproject1` itself it works fine.

I've read https://vitest.dev/guide/workspace.html but didn't see anything that could be related.

Is there a config I'm missing or is this not supported yet? If so, this feature would be very helpful.

**Comment by TECH7Fox** [comment]
Looks like it's just the `rootDir` that is incorrect.
I added my project path to the `rootDir` and it worked.
```
const nuxt = await loadNuxt({
    cwd: rootDir + "/apps/mycyso",
```

What if we can set a relative `rootDir` ourself in the vitest config from the config file itself? Than it would work both workspace and project wide.

**Comment by rinux55** [comment]
> hat if we can set a relative `rootDir` ourself in the vitest config from the config file itself? Than it would work both workspace and project wide.

This would be a great solution for testing a module with a fixture as well.

**Comment by vsanrocha** [comment]
@TECH7Fox, could you please provide some examples with these workspaces? I've been attempting to use them for my project, but I've encountered some challenges and haven't been able to make much progress so far. Your insights would be greatly appreciated!

**Comment by TECH7Fox** [comment]
@vsanrocha I have this in my `vitest.config` in the nuxt project:
```js
import { defineVitestConfig } from "nuxt-vitest/config";

export default defineVitestConfig({
  test: {
    globals: true,
    environment: "nuxt",
    environmentOptions: {
      nuxt: {
        rootDir: __dirname,
      },
    },
});
```

and in the root a `vitest.config` with the coverage settings, and a `vitest.workspace` that points to the projects.
The packages just have a simple `vitest.config` with `defineConfig`.
