### ISSUE TITLE
Dynamic module import seems to be causing error

### ISSUE THREAD

**Issue by Clive-Ward-Cron** [danielroe/nuxt-vitest#196]
My dev dependencies: 
```
{
    "@nuxt/devtools": "^0.5.5",
    "@nuxtjs/tailwindcss": "^6.4.1",
    "@vitest/coverage-c8": "^0.31.3",
    "nuxt": "^3.5.2",
    "nuxt-vitest": "0.8.2",
    "tailwindcss": "^3.3.2",
    "vitest": "^0.31.3"
  }
```

The app is building fine, but trying to start Vitest is causing the following error:
`ERROR  Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

It seems to be breaking down on `const { startVitest } = await import(await resolvePath("vitest/node"));` in `module.mjs`

Is anyone else experiencing this issue with the latest version of Nuxt or is it just me?

**Comment by Clive-Ward-Cron** [comment]
Thank you @danielroe! That solved my issue with module dynamic module resolution.
I am running into another issue now though, and I'm not sure if it should be under a new issue or if its still related some how.

I can't seem to be able to view the GUI now.

![image](https://github.com/danielroe/nuxt-vitest/assets/23231126/72e11393-c8e4-4a25-9ff6-efdc910f6591)

**Comment by danielroe** [comment]
Let's make it a new issue. 👍
