### ISSUE TITLE
Support pinia autoImports

### ISSUE THREAD

**Issue by marr** [danielroe/nuxt-vitest#199]
With the pinia nuxt module you can set `autoImports` in the configuration. I have something like this in mine:

```
pinia: {
  autoImports: [['defineStore', 'definePiniaStore']],
},
```
That allows me to auto import `definePiniaStore` which is a reference to `defineStore`. 

The import is not found when I try to test the store using nuxt-vitest. Is there something nuxt-vitest could do to support them? Or is it something that pinia needs to fix with their module on their end?

**Comment by danielroe** [comment]
Could you provide a repro of what you're trying?

**Comment by marr** [comment]
Yes, thank you for taking a look: https://github.com/marr/nuxt-vitest/commit/fbb1b6499323e084194efd02198046012348d011

With that repro, you can run the `play` command and see that the page renders as expected. The tests do fail to compile, and I am not sure what the solution might be.

**Comment by marr** [comment]
Thank you! I was trying to update snapshots from the root by mistake. Will close this.
