### ISSUE TITLE
custom composable without function name not mocked with `mockNuxtImport`

### ISSUE THREAD

**Issue by rinux55** [danielroe/nuxt-vitest#202]
I have a custom composable (`useConsent`), which I am trying to mock. 
I'm importing the composable like so:

`import { useConsent, useHead } from '#imports'`.

The import is recognized in `packages/vitest-environment-nuxt/src/modules/mock.ts`:
```
{
  name: "default",
  as: "useConsent",
  from: "[...]/src/runtime/composables/useConsent.ts",
  priority: undefined,
}
```

Even though the import is recognized and no `"Cannot find import to mock"` error is thrown, the import is not mocked.
In the same file I am mocking `useHead`, that one is mocked without any issues.

Using `nuxt-vitest@0.8.4`

**Comment by danielroe** [comment]
There is a bug in the latest version of vitest - ensure you are using 0.30.

**Comment by rinux55** [comment]
@danielroe, yes, `vitest` has been pinned to 0.30 in my branch (more stuff would break otherwise), so this may be something else.

**Comment by rinux55** [comment]
@danielroe, I've created this sandbox with the issue: https://stackblitz.com/edit/nuxt-starter-q7qxkk?file=app.spec.ts
Running the tests will fail as the component is not being mocked at the moment. Unless I'm doing something wrong it doesn't seem to work unfortunately!

**Comment by VladimirCores** [comment]
Can't make custom composables work as well. Help needed.

**Comment by VladimirCores** [comment]
I have found the problem - exported function must have the name, not only file name with default import:
![image](https://github.com/danielroe/nuxt-vitest/assets/442111/533fb8a9-653d-4a1f-b6a8-9fd21566cd4c)
cc @rinux55

**Comment by BBoehm** [comment]
@VladimirCores 
That's a nice workaround, thanks!
But it should not be a requirement. Default exports are an essential part of JS and should be supported therefore, so that people don't have to know about this limitation or have to look it up and don't need to adapt existing code.

**Comment by rinux55** [comment]
Thanks @VladimirCores, that workaround works indeed! 
@danielroe are you aware of the limitation with default exports? I think that should be working out of the box as well.

**Comment by danielroe** [comment]
No, there shouldn't be any limitation. I'm assuming your auto-import works fine in Nuxt, right?

**Comment by BBoehm** [comment]
@danielroe 
Yes, auto-import works fine in my project; also seems to work as expected in the sandbox provided by rinux55 above:

> @danielroe, I've created this sandbox with the issue: https://stackblitz.com/edit/nuxt-starter-q7qxkk?file=app.spec.ts Running the tests will fail as the component is not being mocked at the moment. Unless I'm doing something wrong it doesn't seem to work unfortunately!

**Comment by rinux55** [comment]
@danielroe  I'm sorry, I was a bit too quick to say that it works with a named export. I've created a new sandbox with updated nuxt-vitest. 

As it stands now:
 * auto import with default export working ✅ 
 * mocking auto import with a default export using `mockNuxtImport` still doesn't seem to work.
 * auto import with named export is not working at all, but I think this is expected behaviour from nuxt.

https://stackblitz.com/edit/nuxt-starter-t1xglf?file=app.vue

@VladimirCores how did you get auto-imports to work with a named export? With me, it doesn't seem to work at all.

**Comment by rinux55** [comment]
@danielroe I've created a new sandbox with the latest package versions and a new test for named imports.
As it stands now:

 * ✅ Nuxt auto imports work
 * ✅ mocking named exports with `useMockNuxtImport` works
 * 🛑 mocking default exports with `useMockNuxtImport` fails

https://stackblitz.com/edit/nuxt-starter-t1xglf?file=app.test.ts

**Comment by niko-chaffinchicas** [comment]
Ok @danielroe, I believe the PR I just opened should address this issue 👍

**Comment by danielroe** [comment]
resolved in https://github.com/danielroe/nuxt-vitest/pull/334
