### ISSUE TITLE
Package import specifier '#app/entry' not defined

### ISSUE THREAD

**Issue by Clive-Ward-Cron** [danielroe/nuxt-vitest#204]
Thank you @danielroe! That solved my issue with dynamic module resolution.
I am running into another issue now though, and I'm not sure if it should be under a new issue or if its still related some how.

I can't seem to be able to view the GUI now.

![image](https://github.com/danielroe/nuxt-vitest/assets/23231126/72e11393-c8e4-4a25-9ff6-efdc910f6591)

I'm also receiving an unhandled error notification from Vitest.

_Originally posted by @Clive-Ward-Cron in https://github.com/danielroe/nuxt-vitest/issues/196#issuecomment-1572951950_

**Comment by Clive-Ward-Cron** [comment]
This is the error I'm receiving:
```bash
TypeError: Package import specifier "#app/entry" is not defined in package C:\test\node_modules\vitest-environment-nuxt\package.json imported from C:\test\node_modules\vitest-environment-nuxt\dist\index.mjs
 ❯ new NodeError node:internal/errors:399:5
 ❯ importNotDefined node:internal/modules/esm/resolve:350:10
 ❯ packageImportsResolve node:internal/modules/esm/resolve:777:9
 ❯ moduleResolve node:internal/modules/esm/resolve:932:16
 ❯ defaultResolve node:internal/modules/esm/resolve:1153:11
 ❯ nextResolve node:internal/modules/esm/loader:163:28
 ❯ ESMLoader.resolve node:internal/modules/esm/loader:838:30
 ❯ ESMLoader.getModuleJob node:internal/modules/esm/loader:424:18
 ❯ ESMLoader.import node:internal/modules/esm/loader:525:22
 ❯ importModuleDynamically node:internal/modules/esm/translators:110:35
```

**Comment by VegasChickiChicki** [comment]
I have same error...

**Comment by Clive-Ward-Cron** [comment]
I wanted to update this and say that this is no longer an issue for me after I updated **Nuxt to v3.6.3** and **nuxt-vitest to v0.10.0** and installed **happy-dom**.

The tests are running without error and the Nuxt Devtools panel is displaying correctly.
