### ISSUE TITLE
What testing library to use with this environment?

### ISSUE THREAD

**Issue by dmint789** [danielroe/nuxt-vitest#219]
EDIT: the previous title of the issue was 'Error when running Nuxt: Failed to resolve import "fsevents"'

Whenever I run `npm run dev` after doing the set-up from the README, I get this error:

```
Failed to resolve import "fsevents" from "node_modules/.cache/vite/client/deps/chunk-CIY6OCOU.js?v=92df0d45". Does the file exist?
```

`fsevents` is a module only relevant for Mac OS. Why am I getting this error on Linux? As soon as I undo the nuxt-vitest set-up, the error goes away again, and it only showed up for the first time after I added this module to my project. Here is my `vitest.config.js`:

```
import path from 'path';
import { defineVitestConfig } from 'nuxt-vitest/config';
import Vue from '@vitejs/plugin-vue';
import Components from 'unplugin-vue-components/vite';
import AutoImport from 'unplugin-auto-import/vite';

export default defineVitestConfig({
  plugins: [
    Vue(),
    Components({
      dirs: ['components'],
      directoryAsNamespace: true,
    }),
    AutoImport({
      imports: ['vue'],
    }),
  ],
  test: {
    globals: true,
    environment: 'nuxt',
  },
  resolve: {
    alias: {
      '~': __dirname,
      '~~': path.resolve(__dirname, '../'),
    },
  },
});
```

Here is my `nuxt.config.js`:

```
export default defineNuxtConfig({
  ssr: true,
  modules: ['@pinia/nuxt', '@nuxtjs/tailwindcss'],
  css: ['~/assets/css/main.pcss', '@fortawesome/fontawesome-svg-core/styles.css', 'nuxt-vitest'],
  runtimeConfig: {
    public: {
      apiBase: process.env.API_BASE_URL || 'http://localhost:5000/api',
    },
  },
  telemetry: false,
  alias: {
    '~~': '..',
  },
});
```

**Comment by danielroe** [comment]
For a start, you do not need to add any of that configuration to your vitest config any more - just the `test` section.

Would you provide a reproduction?

**Comment by dmint789** [comment]
Hi @danielroe . I know, that's just what I need for my testing environment. I will try to make a reproduction later today.

**Comment by dmint789** [comment]
Ugh, I just realized my dumb mistake. You might notice that I put the nuxt-vitest module in the css array instead of the modules array on accident. I am no longer having an issue with nuxt dev, but now there is a vue router warning when running tests. It looks like this:
```
[Vue Router warn]: No match found for location with path "blank"
```
Right now my vitest config is pretty much just the bare-bones part shown in the README. My test looks like this:
```
import { describe, expect, it, beforeEach } from 'vitest';
import { mount } from '@vue/test-utils';
import { setActivePinia, createPinia } from 'pinia';
import SitePage from '~/pages/SitePage.vue';

describe.concurrent('Kanji Sorter page', () => {
  beforeEach(() => {
    setActivePinia(createPinia());
  });

  it('is rendered', async () => {
    const wrapper = mount(SitePage);
    const title = wrapper.get('[data-test="page_title"]');
    expect(title.text()).toBe('Page Title');
  });
});
```
Does it even make sense that I'm using vue test utils for this? The README doesn't really say what should/can be used for writing the tests, so can you tell me what you personally use with it? I think this would also be useful to include in the README. Does @testing-library/vue work with this test environment?

**Comment by dmint789** [comment]
There is also this error I'm getting when running the test:
```
[nuxt] error caught during app initialization H3Error: Page not found: /blank
```

**Comment by rinux55** [comment]
@dmint789, for the `Page not found: /blank` error, there's this issue you can follow: https://github.com/danielroe/nuxt-vitest/issues/76

> Does it even make sense that I'm using vue test utils for this? The README doesn't really say what should/can be used for writing the tests, so can you tell me what you personally use with it? I think this would also be useful to include in the README. Does @testing-library/vue work with this test environment?

You can use any testing library you want with this, this is just the test environment. `nuxt-vitest` will make sure auto-imports work and the nuxt app is built. Then you can choose any testing library you'd like to use, so using @testing-library/vue is a solid choice!

**Comment by dmint789** [comment]
I see. Thank you for the help! I'll check out that issue and I'll start using testing library.
