### ISSUE TITLE
useRuntimeConfig returns not align to dev mode

### ISSUE THREAD

**Issue by maicss** [danielroe/nuxt-vitest#29]
Same code in source file: `console.log(useRuntimeConfig())`

```
// dev mode
{
  app: { baseURL: '/', buildAssetsDir: '/_nuxt/', cdnURL: '' },
  nitro: { routeRules: { '/__nuxt_error': [Object] }, envPrefix: 'NUXT_' },
  public: {
    enablePreview: true,
    baseDomain: 'http://localhost:3000'
  },
}
```

```
// test mode
{ public: {}, app: { baseURL: '/' } }
```

**Comment by vedmant** [comment]
I have the same issue

**Comment by Ken-vdE** [comment]
I have the same issue

**Comment by floriankapaun** [comment]
The issue that nuxt-vitest ignores the `runtimeConfig` from `nuxt.config.ts` does still occur with the current version. I created a [reproduction repo](https://github.com/floriankapaun/nuxt-vitest-issue-29-reproduction) @danielroe. Hope that helps.

**Comment by floriankapaun** [comment]
Mocking the nuxt auto-import `useRuntimeConfig` as in the following example, results in the error `Cannot find import "useRuntimeConfig" to mock`.
```js
import { mockNuxtImport } from 'vitest-environment-nuxt/utils'

mockNuxtImport('useRuntimeConfig', () => {
  return () => {
    return {
      public: { API_ENTRYPOINT: 'http://api.example.com' }
    }
  }
})
```

**Comment by floriankapaun** [comment]
@danielroe I am willing to help you with this task with a pull request, however I couldn't get it done on my own. If you can give me a hint where the Nuxt instance used in the tests by `nuxt/vitest` is loaded/instantiated, then I could try my luck again.

**Comment by danielroe** [comment]
I agree, this would be a good thing to resolve. We set up the environment here:

https://github.com/danielroe/vitest-environment-nuxt/blob/328098d2e9ea66f7351766b40191e57520d3084e/packages/vitest-environment-nuxt/src/index.ts#L24-L32

And here is where we get access to Nuxt itself:

https://github.com/danielroe/vitest-environment-nuxt/blob/f3ac4274654be7053da3a675c6affeaded37eec0/packages/nuxt-vitest/src/config.ts#L49-L90

There are several possible ways we might be able to resolve this - most promising might be adding a plugin to the Nuxt config to set `__NUXT__` for us?

**Comment by floriankapaun** [comment]
Thanks for pointing me in the right direction @danielroe. 👍
My pull-request provides a very simple solution to this issue. Hope it fits in with the codebases future direction.

**Comment by hecktarzuli** [comment]
It would appear there still is an issue with env overrides like NUXT_PUBLIC_FOO=true making their way into the test env.  They just keep their default values in the nuxt.config.ts file.

**Comment by danielroe** [comment]
Ah yes, we probably need to load `.env` file to improve the integration.
