### ISSUE TITLE
Failed to resolve component: RouterLink

### ISSUE THREAD

**Issue by sky-code** [danielroe/nuxt-vitest#296]
Any usage of NuxtLink lead to an error 

```
[Vue warn]: Failed to resolve component: RouterLink
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <NuxtLink to= { name: 'index', params: { userId: '123' } } class="text-neutral-501" onClick=fn<onLinkClick> > 
  at <UserLink userId="123" ref="VTU_COMPONENT" > 
  at <VTUROOT>
```

[Reproduction](https://stackblitz.com/edit/nuxt-vitest-rgzrs9?file=components%2FUserLink.vue)

**Comment by avishaan** [comment]
I've having the same issue

**Comment by oskarols** [comment]
Hey :wave: 

This isn't working because you're using `mount` from `@nuxt/test-utils`. This is a completely separate package and you should not mix them like this. What you *want* to be using is `mountSuspended` from `nuxt-vitest/utils` :+1: 

So if we adjust your test it would look something like:

```
import { mountSuspended } from 'nuxt-vitest/utils';
import { describe, it, expect } from 'vitest';
import UserLink from '@/components/UserLink.vue';

describe('UserLink', () => {
  it('Component should render', async () => {
    const wrapper = await mountSuspended(UserLink, {
      props: { userId: '123' },
    });

    console.log(wrapper.html());

    expect(wrapper.element.tagName).toBe('A');
  });
});
```

Hope that helps :smile:

**Comment by sky-code** [comment]
Sorry I forgot to mention that my tests based on `@testing-library/vue`, I updated [Reproduction](https://stackblitz.com/edit/nuxt-vitest-frabdm?file=test%2FUserLink.nuxt.test.ts), as you can see from console output `Test component` was rendered which means nuxt environment bootstrapped and works but `RouterLink` still not working correctly.

**Comment by oskarols** [comment]
Using anything else other than `mountSuspended` is not going to work. To use testing-library you need a custom wrapper.

If this is something you want please upvote [this issue](https://github.com/danielroe/nuxt-vitest/issues/271) that I made 😄
