### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'vueApp')

### ISSUE THREAD

**Issue by ngoloc10796** [danielroe/nuxt-vitest#317]
![image](https://github.com/danielroe/nuxt-vitest/assets/28887448/c6fed8ba-c954-4972-a626-dcedd50428a8)
I have do as [example](https://nuxt.com/modules/vitest) but fail  .Please help me!

**Comment by DenFin** [comment]
I am also having problems to setup nuxt-vitest and encountered this error. I setup a repro on [Stackblitz](https://stackblitz.com/edit/nuxt-starter-9cbcji?file=nuxt.config.ts,app.vue,app.test.ts) 

It is basically the example from [here](https://github.com/danielroe/nuxt-vitest/blob/main/playground/tests/nuxt/mock-component-1.spec.ts)

**Comment by danielroe** [comment]
If that fixes the issue then perhaps we can close this in favour of https://github.com/danielroe/nuxt-vitest/issues/289

**Comment by maikaodev** [comment]
@danielroe this solved my problem. But the typescript doesn't recognize -> test: { environment: 'nuxt' }

so i added a @ts-ignore

```javascript
import { fileURLToPath } from 'node:url';
import { defineVitestConfig } from 'nuxt-vitest/config';

export default defineVitestConfig({
// @ts-ignore
  test: {
    environment: 'nuxt',
  },
})



```

**Comment by danielroe** [comment]
now that is strange. any chance of a reproduction?

**Comment by ngoloc10796** [comment]
> @DenFin downgrade vitest to 0.33.0 and set the environment to nuxt.
> 
> Do so by editing the vitest.config.ts
> 
> ```ts
> import { fileURLToPath } from 'node:url';
> import { defineVitestConfig } from 'nuxt-vitest/config';
> 
> export default defineVitestConfig({
>   test: {
>     environment: 'nuxt',
>   },
> });
> ```
> 
> or add `// @vitest-environment nuxt` on top of your files.
> 
> https://stackblitz.com/edit/nuxt-starter-ut1vgi?file=app.test.ts

Worked for me. Thank you!
