### ISSUE TITLE
Vite `4.4.9` is causing `Unexpected character '@'` errors

### ISSUE THREAD

**Issue by gbyesiltas** [danielroe/nuxt-vitest#325]
Hello there,

I'm using `nuxt-vitest: 0.10.4` and `vite: 4.3.9` and everything is working fine but when I tried to update vite to `4.4.9` I started getting a bunch of `Unexpected character '@'` errors from my decorators. At first I thought I'd open the issue in the `vitejs` repo but the project itself seems to run fine with the updated vite so I ended up opening it here instead, thanks :)

<img width="875" alt="Screenshot 2023-09-04 at 16 30 40" src="https://github.com/danielroe/nuxt-vitest/assets/50772478/adeae970-7d0f-400c-a571-707950997496">

**Comment by danielroe** [comment]
Would you be able to provide a reproduction? 🙏

**Comment by gbyesiltas** [comment]
Hey @danielroe thanks for the quick reply! Having a few busy days now but I will add a reproduction as soon as I can 😅

**Comment by gbyesiltas** [comment]
Heyo, update here. When I tried to update the Nuxt version to `3.7.x`, I started getting the same error in the actual project as well. After some investigation and trial-error, I could solve it [this way](https://github.com/nuxt/nuxt/issues/21756#issuecomment-1727226259). It fixed it both for the project and the tests :)
