### ISSUE TITLE
`@testing-render/vue` is needed when using a util

### ISSUE THREAD

**Issue by huang-julien** [danielroe/nuxt-vitest#330]
````
import * as _testing_library_vue from '@testing-library/vue';
import { RenderOptions as RenderOptions$1 } from '@testing-library/vue';
````

is being inlined in `vitest-environment-nuxt/dist/utils`, forcing the user to install `@testing-library/vue` if they use any utils provided by `vitest-environment-nuxt` even if they don't use `renderSuspended()`

**Comment by VegasChickiChicki** [comment]
@danielroe Hi, still not working. 0.10.5 version :C

Error: Could not resolve "@testing-library/vue" imported by "vitest-environment-nuxt". Is it installed?

I can't uderstand, i need install @testing-library/vue or no?

**Comment by danielroe** [comment]
are you using `renderSuspended`?

**Comment by VegasChickiChicki** [comment]
> are you using `renderSuspended`?

Yes, like this:

```
import { describe, it } from 'vitest';
import { renderSuspended } from 'nuxt-vitest/utils';

import TheFooter from './the-footer.vue';



describe('render', () => {
	it('base render(snapshot)', async () => {
		const wrapper = await renderSuspended(TheFooter);
		
		expect(wrapper.html()).toMatchSnapshot();
	});
});
```

**Comment by danielroe** [comment]
Then, yes, you need to install `@testing-library/vue` as it is used under the hood with `renderSuspended`.

**Comment by VegasChickiChicki** [comment]
> Then, yes, you need to install `@testing-library/vue` as it is used under the hood with `renderSuspended`.

Okay, i understand. I think maybe this need add to documentation?
