### ISSUE TITLE
Error: [nuxt] instance unavailable

### ISSUE THREAD

**Issue by rafaeldsousa** [danielroe/nuxt-vitest#340]
Hi Daniel.

I keep getting `Error: [nuxt] instance unavailable` in my project for tests that require runtime access.

I've forked your example and that works as expected, even on a forked version. 

But then if I start a new Nuxt 3 project and add the dependencies for the same two tests you have in the example
- nuxt-vistest
- vitest
- @nuxt/test-utils

<img width="563" alt="Screenshot 2023-09-19 at 7 05 24 PM" src="https://github.com/danielroe/nuxt-vitest/assets/39249777/1061f31e-802f-464c-88d1-850b8c907ac1">

And then run the tests I get the exact same error as I'm facing on my project. Here is the link where the error can be seen. https://stackblitz.com/edit/nuxt-starter-yvefws

I use yarn on my project, but the error is exactly the same as the one on the sample project above.
Could you tell me if I'm missing something, I can't quite see much difference when comparing the samples.

**Comment by danielroe** [comment]
See https://github.com/danielroe/nuxt-vitest#conflict-with-nuxttest-utils.
