### ISSUE TITLE
[Vue Router warn]: No match found for location with path "blank"

### ISSUE THREAD

**Issue by ivan-barragan** [danielroe/nuxt-vitest#76]
Whenever I run any unit test with a file with `*.nuxt.spec.*` in the name I get the following errors:

```
[Vue Router warn]: No match found for location with path "blank"
[Vue Router warn]: No match found for location with path "blank"
[Vue Router warn]: No match found for location with path "blank"
[Vue Router warn]: No match found for location with path "/blank"
```
I've tried mocking the router and also [creating a new router](https://test-utils.vuejs.org/guide/advanced/vue-router.html#using-a-real-router) but nothing seems to help.

ModalShell.nuxt.spec.ts
```
import { describe, it, beforeEach, expect } from 'vitest'
import { VueWrapper } from '@vue/test-utils'
import { mountWrapper } from '@/tests/testUtils'
import ModalShell from '@/components/shared/ModalShell.vue'

describe('Invite Members Modal', () => {
  let wrapper: VueWrapper

  beforeEach(() => {
    wrapper = mountWrapper({
      component: ModalShell,
    })
  })

  it('matches snapshot', () => {
    expect(wrapper.html()).toMatchSnapshot()
  })
})
```

testUtils.ts
```
import { shallowMount, RouterLinkStub } from '@vue/test-utils'
import { createTestingPinia } from '@pinia/testing'
import { createI18n } from 'vue-i18n'
import messages from '@/lang/messages'

interface MountConfig {
  component?: object
  initialState?: object
  props?: object
}

export function mountWrapper({ component, initialState, props }: MountConfig) {
  const i18n = createI18n({
    legacy: false,
    globalInjection: true,
    locale: 'en',
    messages,
  })

  return shallowMount(component as object, {
    global: {
      plugins: [
        createTestingPinia({
          initialState,
        }),
        i18n,
      ],
      stubs: {
        NuxtLink: RouterLinkStub,
      },
    },
    props,
  })
}

export { createTestingPinia }
```

Any help is appreciated. Thanks

**Comment by ndragun92** [comment]
![image](https://user-images.githubusercontent.com/39500267/224162910-5c927c37-94ef-4a9f-8443-11f8089e896d.png)
Getting the same error

**Comment by nourspace** [comment]
I'm using pure vue3 setup and getting the same error, even when importing the actual router in my tests.

**Comment by jaywilburn** [comment]
Any ideas?

**Comment by ivan-barragan** [comment]
The only workaround/hack I found was to create a page named `blank.vue`. Obviously that's not ideal but it stops the warnings at least.

**Comment by jaywilburn** [comment]
Thanks @ivan-barragan - I believe we shouldn't have to add a blank page, so I am wondering if there is something else we can do or is this something being figured out in the next release. cc @danielroe

**Comment by PavelGonzales** [comment]
I have a same problem :(

**Comment by DanielleConstell** [comment]
Also having this issue

**Comment by eatsmarter-benny** [comment]
Still present, even with version 0.7.0 of the module in a vanilla Nuxt 3.4.2 environment with @vue/test-utils 2.3.2 and vitest 0.30.1 installed.

**Comment by lassediercks** [comment]
was anyone able to create a minimal reproduction for this?

**Comment by ouuan** [comment]
https://github.com/ouuan/nuxt-vitest-76-reproduction

**Comment by lassediercks** [comment]
`navigateTo` with a nested route also navigate to `/blank` 

https://stackblitz.com/edit/nuxt-vitest-fv5tbr?file=test%2Fapp.nuxt.spec.ts,pages%2Fsubfolder%2F[slug].vue

**Comment by bmoret** [comment]
I think the module is dependent on the [...slug].vue page in the testing repo to work, adding this to my repository fixed it

**Comment by lassediercks** [comment]
@bmoret while this may be a solution in your case technically that's a catchall route all which is most likely not want one wants to use as a workaround

**Comment by bmoret** [comment]
Oh i definitely agree, I meant that it got rid of the error message!

Op do 22 jun. 2023 10:50 schreef Lasse Diercks ***@***.***>:

**Comment by lassediercks** [comment]
yeah I checked that after re-reeading and felt my comment was not adequate anymore thus removed it

**Comment by Jesse1989pp** [comment]
> `navigateTo` with a nested route also navigate to `/blank`
> 
> [https://stackblitz.com/edit/nuxt-vitest-fv5tbr?file=test%2Fapp.nuxt.spec.ts,pages%2Fsubfolder%2F[slug].vue](https://stackblitz.com/edit/nuxt-vitest-fv5tbr?file=test%2Fapp.nuxt.spec.ts,pages%2Fsubfolder%2F%5Bslug%5D.vue)

Been trying to work with this example. Issue has morphed a bit since v0.8.6. The blank path seemed to be coming from `happy-dom` and [this change](https://github.com/danielroe/nuxt-vitest/commit/674ede32d866a34cf5c300097cc25a6012b5adaf) has now made the navigation to go to `/` first. Example with latest version: https://stackblitz.com/edit/nuxt-vitest-mtv3z5

**Comment by danielroe** [comment]
yes, let's track this as a separate issue.
