### ISSUE TITLE
Add option to replace `happy-dom` with `jsdom`

### ISSUE THREAD

**Issue by enkot** [danielroe/nuxt-vitest#81]
Because `happy-dom` is not fully compatible with `jsdom`, we can't use, for example, `@testing-library/jest-dom` within the Nuxt environment. 
I suggest to add possibility to replace `happy-dom` with `jsdom`, `@happy-dom/jest-environment` etc.

**Comment by AndrewBogdanovTSS** [comment]
@danielroe is there any updates regarding this?

**Comment by danielroe** [comment]
I would be very happy for a PR that allows this to be configurable.
