### ISSUE TITLE
mountSuspended helper doesn't accept options

### ISSUE THREAD

**Issue by ghazialhouwari** [danielroe/nuxt-vitest#87]
I have some components with `async setup` that require props, slots and other `MountOptions`. It'd be helpful if `mountSuspended` supports `MountOptions`.

### Expected behavior
```
const component = await mountSuspended(SomeComponent, {
  props: {
    foo: 'bar',
  },
  ...
})
```

**Comment by maartenvanhunsel** [comment]
@ghazialhouwari let's extend the mountOptions by the last PR @danielroe made for `options.route`. See https://github.com/danielroe/nuxt-vitest/pull/154/files#diff-d4c4281072871672195289d5adc0accb5595279f487557d1f32783f389bd3507R33
