### ISSUE TITLE
Provide a simple working example from Stackblitz

### ISSUE THREAD

**Issue by Kobee1203** [danielroe/nuxt-vitest#88]
- Nuxt: 3.1.1
- nuxt-vitest: 0.6.8

I followed the documentation to test the library.
I created a test file that mocks 'useStorage'.
When I run the tests, I get an error:

`Error: Cannot find import "useStorage" to mock`

Do I need to configure anything else?

Here is my example on Stackblitz:\
https://stackblitz.com/edit/nuxt-starter-dllgrr?file=tests%2Fmytest.nuxt.test.ts

Could you provide an example that works on Stackblitz?

**Comment by ghazialhouwari** [comment]
I believe the provided example is meant to mock `useStorage` from [VueUse](https://vueuse.org/) which can't be auto-imported as mentioned in the [official docs](https://vueuse.org/core/useStorage/). However, there's an issue with importing extend modules. I had the same issue when I mocked `useI18n`

As for providing working examples, please refer to this issue [this issue](https://github.com/danielroe/nuxt-vitest/issues/5)

cc: @antfu

**Comment by hennihaus** [comment]
Any updates here?

**Comment by danielroe** [comment]
Yes, the `useStorage` example requires you have an auto-import of that name, which `@vueuse/nuxt` provides.

Here's an updated version of your repro: https://stackblitz.com/edit/nuxt-starter-2keskx?file=tests/mytest.nuxt.test.ts.
